apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/tracking-id: kong
spec:
  project: platform

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  source:
    chart: kong
    repoURL: https://charts.konghq.com
    targetRevision: 2.52.0

    helm:
      values: |
        ingressController:
          enabled: true

        controller:
          args:
            - --feature-gates=GatewayAlpha=true

        admin:
          enabled: true

        proxy:
          type: NodePort

        env:
          database: "off"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
